kind: Template
apiVersion: v1
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      labels:
        app: artemis-credentials-secret
      name: artemis-credentials-secret
    stringData:
      broker-url: ${BROKER_URL}
      username: ${USERNAME}
      password: ${PASSWORD}
      trustStorePassword: ${TRUSTSTORE_PASSWORD}
parameters:
  - name: USER_NAMESPACE
    required: true
  - name: BROKER_URL
    required: true
  - name: USERNAME
    required: true
  - name: PASSWORD
    required: true
  - name: TRUSTSTORE_PASSWORD
    required: true    